### ISSUE TITLE
Kotlin home directory (Optional[/.okbuck/workspace/kotlin_home:kotlin_home]) specified in .buckconfig was not found.

### ISSUE THREAD

**Issue by Blisse** [uber/okbuck#798]
I'm seeing the following errors in my logs after running `./buckw project`, which is preventing us from updating from OkBuck 0.45.3 to 0.46.0+.

```
Kotlin home directory (Optional[/.okbuck/workspace/kotlin_home:kotlin_home]) specified in .buckconfig was not found.
    When creating rules for //common/utilities/pure:src_main#class-abi.
    When creating rules for //common/utilities/pure:src_main.
```

The file in `.okbuck/config/okbuck.buckconfig` contains:

```
[kotlin]
    kotlin_home = .okbuck/workspace/kotlin_home:kotlin_home
```

On 0.45.0, it was:

```
[kotlin]
    kotlin_home = .okbuck/workspace/kotlin_home
```

Any ideas on how to resolve this? We do not have the kotlin version configured for okbuck, e.g. not the lines below, but adding it doesn't change the error. 
``` 
okbuck {
  kotlin {
    version = rootProject.ext.kotlinVersion
  }
}
```

**Comment by kageiit** [comment]
This is fixed in https://github.com/uber/okbuck/pull/784 imo. Can you upgrade to 0.46.2 and try?

**Comment by Blisse** [comment]
Nothing appeared to change between 0.46.0 or 0.46.2 unfortunately.

**Comment by kageiit** [comment]
@raviagarwal7 can you PTAL?

**Comment by raviagarwal7** [comment]
please use buck version 91b30eb54128130f925c3d968619c5b59c888486 or older for latest okbuck to work. I am looking into fixing this on buck master as it was reverted in 01ae6e7c43d35a55118622d7ab91e087008e852f

**Comment by Archinamon** [comment]
Hi! For the latest commit df5052037f04ae1a6afc7e393c904f6e316ae556 and OkBuck 0.46.5 same error occurs :(
Any workaround for this?

With the bundled buck binary I've got `ClassNotFoundException: gnu.trove.THashMap` starting kotlinc inside buck :(

**Comment by mmdango** [comment]
Same boat here, latest buck does not work for me. We are on a fairly old version. Would love to update.

**Comment by kageiit** [comment]
if you revert https://github.com/facebook/buck/commit/01ae6e7c43d35a55118622d7ab91e087008e852f on latest buck, you can still update

**Comment by Archinamon** [comment]
I did revert and have built buck w/o 01ae6e7 commit.
Still have exception during kotlinc on my module:
```
 ./buckw build //app:bin_debug --deep
Building: finished in 0.4 sec (100%) 891/903 jobs, 2 updated
  Total time: 0.5 sec
Buck encountered an internal error
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:209)
        at com.facebook.buck.jvm.kotlin.KotlincStep.execute(KotlincStep.java:96)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:46)
        ... 16 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:200)
        ... 18 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.cli.common.messages.MessageRenderer
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
        ... 23 more

    When running <kotlinc>.
    When building rule //ipc-dto:src_debug.
```

Any points how to avoid it?

**Comment by kageiit** [comment]
which version of kotlin are you on?

**Comment by kageiit** [comment]
This is fixed in #802

**Comment by kageiit** [comment]
Fixed in v0.47.0

**Comment by Blisse** [comment]
Thanks! This was fixed by bumping to 47, cheers!

**Comment by lavekush-t** [comment]
Again facing the similar issue in `0.47.2`

```
Kotlin home directory (Optional[/.okbuck/workspace/kotlin_home:kotlin_home]) specified in .buckconfig was not found.
    When creating rules for //tkpddesign:src_debug#class-abi.
    When creating rules for //tkpddesign:src_debug.
```

**Comment by kageiit** [comment]
Have you tried https://github.com/uber/okbuck/issues/798#issuecomment-461251076 ?

**Comment by erawhctim** [comment]
@kageiit Apologies for the ignorance, but do you have some lightweight instructions on how to get this setup properly? I'm still seeing this issue on 0.47.1, and when I checkout okbuck master and attempt to revert that commit, it fails and says the commit ID is invalid.

**Comment by kageiit** [comment]
I think all that is needed right now is to revert https://github.com/facebook/buck/commit/01ae6e7c43d35a55118622d7ab91e087008e852f

It should work with latest buck and okbuck by reverting that commit. What issue are you seeing

**Comment by erawhctim** [comment]
I'm just unsure of how to go about doing that - do I need to clone buck locally and revert the commit there, and then tell my local copy of okbuck to use that copy of buck itself, and then build okbuck manually? Just trying to figure out to test this

**Comment by kageiit** [comment]
Make a fork of buck on github, then use https://github.com/facebook/buck#prebuilt-buck-binaries to point at your fork by letting okbuck know via the extension https://github.com/uber/okbuck/wiki/OkBuck-options-and-examples

```
okbuck
{
    // Set a specific buck binary or alternate buck distribution.
    buckBinary = "com.github.forkk:buck:fc8f977a04b2847c6707668a73320ad336d20527@pex"
}
```

**Comment by fangzhzh** [comment]
it's reproduced in 

    classpath 'com.uber:okbuck:0.48.4'
    ext.kotlin_version = '1.3.41'
    ext.kotlin_coroutine_version = '1.2.1'
